shopify.settings:
  type: config_object
  label: 'Shopify settings'
  mapping:
    api:
      type: mapping
      label: 'API connection settings'
      mapping:
        domain:
          type: string
          label: 'Store domain'
        key:
          type: string
          label: 'API key'
        password:
          type: string
          label: 'Password'
        secret:
          type: string
          label: 'Shared secret'
